DROP TABLE IF EXISTS PRODUCTS;

CREATE TABLE PRODUCTS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name_product VARCHAR(250) NOT NULL,
  price INT NOT NULL,
  category_product VARCHAR(250) NOT NULL,
  supplier_id INT NOT NULL
);

DROP TABLE IF EXISTS SUPPLIERS;

CREATE TABLE SUPPLIERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name_supplier VARCHAR(250) NOT NULL,
  country VARCHAR(250) NOT NULL
);

ALTER TABLE PRODUCTS
    ADD FOREIGN KEY (supplier_id)
    REFERENCES SUPPLIERS(id);
